# stages:
#   - fetch_gdb
#   - pre_check
#   - static_analyzers
#   - build_openocd
#   - build_idf5.0.x
#   - build_idf5.1.x
#   - build_idf5.2.x
#   - build_idf5.3.x
#   - build_idf5.4.x
#   - build_idf_master
#   - build_nuttx
#   - test_idf5.0.x
#   - test_idf5.1.x
#   - test_idf5.2.x
#   - test_idf5.3.x
#   - test_idf5.4.x
#   - test_idf_master
#   - test_host
#   - test_nuttx
#   - coverage
#   - sanitizer_test_idf5.0.x
#   - sanitizer_test_idf5.1.x
#   - sanitizer_test_idf5.2.x
#   - sanitizer_test_idf5.3.x
#   - sanitizer_test_idf5.4.x
#   - sanitizer_test_idf_master
#   - sanitizer_test_nuttx
#   - sanitizer_check_idf5.0.x
#   - sanitizer_check_idf5.1.x
#   - sanitizer_check_idf5.2.x
#   - sanitizer_check_idf5.3.x
#   - sanitizer_check_idf5.4.x
#   - sanitizer_check_idf_master
#   - sanitizer_check_nuttx
#   - deploy
#   - private_deploy
#   - pre_release
#   - release_stage1

stages:
  - static_analyzers
  - build_openocd

image: $CI_DOCKER_REGISTRY/openocd-ci-env:1

default:
  interruptible: true
  retry:
    max: 2
    when: runner_system_failure

variables:

  #
  # System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j4 --no-keep-going"

  GCOV_BUILD_OPTS: ""

  # OpenOCD configuration options
  OPENOCD_CONFIGURE_OPTS: "--disable-doxygen-html --enable-remote-bitbang"

  # GitHub Tool options
  GITHUB_USER: "${GH_USER}"
  GITHUB_REPO: "${GH_REPO}"
  GITHUB_TOKEN: "${GH_TOKEN}"

  #
  # CI settings

  # GIT_STRATEGY is not defined here, an option from "CI / CD Settings"- "General pipelines" is used.
  GIT_SUBMODULE_STRATEGY: none

  #
  # Customization of jobs

  DIST_ART_DIR: "dist"
  DIST_INSTALLED_DIR: "${CI_PROJECT_NAME}"
  ARCHIVE_TOOL: "tar czf"
  ARCHIVE_EXT: "tar.gz"
  RELEASE_DESC: "New release"

before_script:
  - set -o errexit; set -o pipefail; set -o nounset
  - test "${DEBUG_SHELL:-''}" = "1" && set -x

include:
  - '.gitlab/ci/util.yml'
  - '.gitlab/ci/build.yml'
