stages:
  - pre_check
  - static_analyzers
  - build_openocd
  - stub_build_test
  - run_test_pipelines
  - results

image: $CI_DOCKER_REGISTRY/openocd-ci-env:1

default:
  interruptible: true
  retry:
    max: 2
    when: runner_system_failure
    exit_codes: 75

variables:

  #
  # System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j4 --no-keep-going"

  GCOV_BUILD_OPTS: ""

  # OpenOCD configuration options
  OPENOCD_CONFIGURE_OPTS: "--disable-doxygen-html --enable-remote-bitbang"

  # GitHub Tool options
  GITHUB_USER: "${GH_USER}"
  GITHUB_REPO: "${GH_REPO}"
  GITHUB_TOKEN: "${GH_TOKEN}"

  #
  # CI settings

  # GIT_STRATEGY is not defined here, an option from "CI / CD Settings"- "General pipelines" is used.
  GIT_SUBMODULE_STRATEGY: none

  #
  # Customization of jobs

  DIST_ART_DIR: "dist"
  DIST_INSTALLED_DIR: "${CI_PROJECT_NAME}"
  ARCHIVE_TOOL: "tar czf"
  ARCHIVE_EXT: "tar.gz"
  RELEASE_DESC: "New release"

before_script:
  - set -o errexit; set -o pipefail; set -o nounset
  - test "${DEBUG_SHELL:-''}" = "1" && set -x

pipeline_variables:
  stage: pre_check
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - >
      echo "TRIGGERED_BY_GDB_PIPELINE_BRANCH=${TRIGGERED_BY_GDB_PIPELINE_BRANCH:-}" >> variables.env;
      if [[ ! -z ${TRIGGERED_BY_GDB_PIPELINE_BRANCH:-} ]]; then
        echo "CI_FULL_RUN=0" >> variables.env;
      elif [[ $CI_PIPELINE_SOURCE != "push" || ${CI_COMMIT_BRANCH:-} == "master" || ! -z ${CI_COMMIT_TAG:-} ]]; then
        echo "CI_FULL_RUN=1" >> variables.env;
      else
        api_call="https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/67/merge_requests?source_branch=${CI_COMMIT_REF_NAME}&state=opened";
        echo "${api_call}";
        OPEN_MR=$(curl --header "PRIVATE-TOKEN: ${ESPCI_TOKEN}" "${api_call}");
        echo $OPEN_MR;
        ready=$(echo "$OPEN_MR" | python3 -c "import json; x=json.loads(input()); print(1 if len(x) and 'labels' in x[0] and 'ready_to_merge' in x[0]['labels'] else 0)");
        echo "CI_FULL_RUN=${ready}" >> variables.env;
      fi
  artifacts:
    reports:
      dotenv: variables.env

mr_auto_approve:
  stage: results
  tags:
    - build
  dependencies:
    - pipeline_variables
  when: on_success
  script:
    - >
      if [[ -z ${TRIGGERED_BY_GDB_PIPELINE_BRANCH:-} &&  $CI_PIPELINE_SOURCE == "push" && ${CI_COMMIT_BRANCH:-} != "master" ]]; then
        api_call="https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/67/merge_requests?source_branch=${CI_COMMIT_REF_NAME}&state=opened";
        echo "${api_call}";
        OPEN_MR=$(curl --header "PRIVATE-TOKEN: ${ESPCI_TOKEN}" "${api_call}");
        echo $OPEN_MR;
        iid=$(echo "$OPEN_MR" | python3 -c "import json; x=json.loads(input()); print(x[0]['iid'] if len(x) and 'iid' in x[0] else 0)");
        target=$(echo "$OPEN_MR" | python3 -c "import json; x=json.loads(input()); print(x[0]['target_branch'] if len(x) and 'target_branch' in x[0] else '')");
        if [[ $iid != "0" && $target == "master" ]]; then
          action="unapprove"
          if [[ $CI_FULL_RUN == "1" ]]; then
            action="approve"
          fi
          api_call="https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/67/merge_requests/${iid}/${action}";
          echo "${api_call}";
          curl --request POST --header "PRIVATE-TOKEN: ${ESPCI_TOKEN}" "${api_call}";
        fi
      fi

include:
  - '.gitlab/ci/util.yml'
  - '.gitlab/ci/build.yml'
  - '.gitlab/ci/pre-check.yml'
  - '.gitlab/ci/test-stub.yml'
  - '.gitlab/ci/run-pipeline.yml'
