stages:
  - fetch_tools
  - build
  - test
  - results

image: $CI_DOCKER_REGISTRY/openocd-ci-env:1

default:
  interruptible: true
  retry:
    max: 2
    when: runner_system_failure
    exit_codes: 75

variables:
  DIST_ART_DIR: "dist"
  DIST_INSTALLED_DIR: "${CI_PROJECT_NAME}"

fetch_gdb:
  stage: fetch_tools
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  needs:
    - project: idf/binutils-gdb
      job: pack-xtensa-arm-linux-gnueabihf
      ref: $TRIGGERED_BY_GDB_PIPELINE_BRANCH
      artifacts: true
    - project: idf/binutils-gdb
      job: pack-riscv32-arm-linux-gnueabihf
      ref: $TRIGGERED_BY_GDB_PIPELINE_BRANCH
      artifacts: true
    - project: idf/binutils-gdb
      job: pack-xtensa-aarch64-linux-gnu
      ref: $TRIGGERED_BY_GDB_PIPELINE_BRANCH
      artifacts: true
    - project: idf/binutils-gdb
      job: pack-riscv32-aarch64-linux-gnu
      ref: $TRIGGERED_BY_GDB_PIPELINE_BRANCH
      artifacts: true
  rules:
    - if: '$TRIGGERED_BY_GDB_PIPELINE_BRANCH != "" && $CI_IDF_VERSION == "6_1"'
  script:
    - mv dist gdb
    - cd gdb
    - tar -xzf xtensa-esp-elf-gdb*aarch64-linux-gnu.tar.gz
    - tar -xzf riscv32-esp-elf-gdb*aarch64-linux-gnu.tar.gz
    - mv xtensa-esp-elf-gdb xtensa-esp-elf-gdb_arm64
    - mv riscv32-esp-elf-gdb riscv32-esp-elf-gdb_arm64
    - tar -xzf xtensa-esp-elf-gdb*arm-linux-gnueabihf.tar.gz
    - tar -xzf riscv32-esp-elf-gdb*arm-linux-gnueabihf.tar.gz
    - mv xtensa-esp-elf-gdb xtensa-esp-elf-gdb_armhf
    - mv riscv32-esp-elf-gdb riscv32-esp-elf-gdb_armhf
    - rm -f riscv32-esp-elf-gdb*.tar.gz xtensa-esp-elf-gdb*.tar.gz
  artifacts:
    paths:
      - gdb

fetch_gcov:
  stage: fetch_tools
  tags:
    - build
    - internet
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_IDF_VERSION != "5_2" && $CI_IDF_VERSION != "5_3"'
  script:
    - eval "toolchain_version=\$ESP_V${CI_IDF_VERSION}X_TOOLCHAIN_VER"
    - toolchain_suffix=${toolchain_version#esp-}
    - gcc_version=${toolchain_suffix%%_*}
    - >
      for platform in arm-linux-gnueabihf aarch64-linux-gnu; do
        dest=gcov/${toolchain_version}-gcov/${platform};
        mkdir -p ${dest}/bin;
        for arch in riscv32 xtensa; do
          wget -nv https://github.com/espressif/crosstool-NG/releases/download/${toolchain_version}/${arch}-esp-elf-${toolchain_suffix}-${platform}.tar.gz -O toolchain.tar.gz;
          tar -xzf toolchain.tar.gz;
          cp ${arch}-esp-elf/bin/${arch}-esp*-elf-gcov ${dest}/bin;
          mkdir -p ${dest}/lib/gcc/${arch}-esp-elf/${gcc_version};
          cp ${arch}-esp-elf/lib/gcc/${arch}-esp-elf/${gcc_version}/libgcov.a ${dest}/lib/gcc/${arch}-esp-elf/${gcc_version};
        done
        for _chip in esp32 esp32s2 esp32s3; do
          mkdir -p ${dest}/lib/gcc/xtensa-esp-elf/${gcc_version}/${_chip};
          cp xtensa-esp-elf/lib/gcc/xtensa-esp-elf/${gcc_version}/${_chip}/libgcov.a ${dest}/lib/gcc/xtensa-esp-elf/${gcc_version}/${_chip}/;
        done;
        cp xtensa-esp-elf/lib/xtensa_esp*.so ${dest}/lib;
      done
    - rm -rf riscv32-esp-elf xtensa-esp-elf *.tar.gz;
  artifacts:
    paths:
      - gcov

dummy_job:
  script: echo "Pipeline skipped"
  tags:
    - build
  rules:
    - if: '$CI_FULL_RUN == "0" && $CI_IDF_VERSION != "6_1"'

include:
  - '.gitlab/ci/downstream/build-test-app-template.yml'
  - '.gitlab/ci/util.yml'
  - '.gitlab/ci/test-template.yml'
