/* SPDX-License-Identifier: GPL-2.0-or-later */

/***************************************************************************
 *   ESP32-S3 flasher stub definitions                                     *
 *   Copyright (C) 2021 Espressif Systems Ltd.                             *
 ***************************************************************************/
#ifndef OPENOCD_LOADERS_FLASH_ESPRESSIF_ESP32S3_STUB_FLASHER_CHIP_H
#define OPENOCD_LOADERS_FLASH_ESPRESSIF_ESP32S3_STUB_FLASHER_CHIP_H

#include <esp32s3/rom/spi_flash.h>
#include <esp32s3/rom/miniz.h>
#include <esp32s3/rom/opi_flash.h>
#include <esp32s3/rom/sha.h>
#include <stub_xtensa_common.h>

enum {
	ESP32S3_STUB_FLASH_STATE_SPI_USER_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_USER1_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_USER2_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_SLAVE_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_CTRL_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_CLOCK_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_CMD_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_ADDR_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_MS_DLEN_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_MISC_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_CONF_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_SLAVE1_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_CLK_GATE_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DIN_MODE_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DIN_NUM_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DOUT_MODE_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_INT_ENA_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_INT_CLR_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_INT_RAW_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_INT_ST_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DMA_INT_SET_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W0_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W1_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W2_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W3_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W4_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W5_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W6_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W7_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W8_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W9_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W10_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W11_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W12_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W13_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W14_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_W15_REG_ID,
	ESP32S3_STUB_FLASH_STATE_SPI_DATE_REG_ID,
	ESP32S3_STUB_FLASH_STATE_REGS_NUM
};

struct stub_flash_state {
	bool cache_enabled;
	bool spi_regs_saved;
	uint32_t spi_regs[ESP32S3_STUB_FLASH_STATE_REGS_NUM];
	uint32_t dummy_len_plus;
};
void stub_flash_state_prepare(struct stub_flash_state *state);
void stub_flash_state_restore(struct stub_flash_state *state);

#endif	/* OPENOCD_LOADERS_FLASH_ESPRESSIF_ESP32S3_STUB_FLASHER_CHIP_H */
