/* SPDX-License-Identifier: GPL-2.0-or-later */

#define OPENOCD_STUB_BSS_SIZE 0x0000038UL
#define OPENOCD_STUB_STACK_SIZE 512
#define OPENOCD_STUB_PARAM_SIZE 512
#define OPENOCD_STUB_BP_SECTOR_SIZE 4096
