#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Build platform-specific wheel from OpenOCD distribution archive.

Usage:
    python tools/build_wheel.py <dist_archive> <output_dir>

Example:
    python tools/build_wheel.py dist/openocd-esp32-linux-amd64-0.12.0-esp32-20260424.tar.gz wheelhouse/
"""

import argparse
import re
import shutil
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

PLATFORM_MAP = {
    "linux-amd64": "manylinux_2_17_x86_64.manylinux2014_x86_64",
    "linux-arm64": "manylinux_2_17_aarch64.manylinux2014_aarch64",
    "linux-armhf": "manylinux_2_17_armv7l.manylinux2014_armv7l",
    "linux-armel": "linux_armv6l",
    "macos": "macosx_10_9_x86_64",
    "macos-arm64": "macosx_11_0_arm64",
    "win32": "win32",
    "win64": "win_amd64",
}


def extract_archive(archive_path: Path, dest_dir: Path) -> Path:
    """Extract tar.gz or zip archive, return path to extracted content root."""
    dest_dir.mkdir(parents=True, exist_ok=True)

    if archive_path.name.endswith((".tar.gz", ".tgz")):
        with tarfile.open(archive_path, "r:gz") as tar:
            if sys.version_info >= (3, 12):
                tar.extractall(dest_dir, filter="data")
            else:
                tar.extractall(dest_dir)
    elif archive_path.suffix == ".zip":
        with zipfile.ZipFile(archive_path, "r") as zf:
            zf.extractall(dest_dir)
    else:
        raise ValueError(f"Unknown archive format: {archive_path}")

    items = [p for p in dest_dir.iterdir() if not p.name.startswith(".")]
    if len(items) == 1 and items[0].is_dir():
        return items[0]
    return dest_dir


def normalize_version(version: str) -> str:
    """
    Convert version string to PEP 440 format.

    PyPI rejects local version segments (PEP 440 `+label`), so the project
    label (e.g. "esp32") in the upstream tag is dropped. The post-release
    date already disambiguates builds.

    Examples:
        0.12.0-esp32-20260424 -> 0.12.0.post20260424
        0.12.0-20260424       -> 0.12.0.post20260424
        v0.12.0               -> 0.12.0
    """
    version = version.lstrip("v")

    match = re.match(r"^(\d+\.\d+\.\d+)-\w+-(\d+)$", version)
    if match:
        base, date = match.groups()
        return f"{base}.post{date}"

    match = re.match(r"^(\d+\.\d+\.\d+)-(\d+)$", version)
    if match:
        base, date = match.groups()
        return f"{base}.post{date}"

    return version


def parse_archive_name(archive_path: Path, project_prefix: str) -> tuple:
    """Extract platform name and PEP 440 version from archive filename."""
    name = archive_path.name

    if name.endswith(".tar.gz"):
        name = name[:-7]
    elif name.endswith(".tgz"):
        name = name[:-4]
    elif name.endswith(".zip"):
        name = name[:-4]

    prefix = f"{project_prefix}-"
    if not name.startswith(prefix):
        raise ValueError(
            f"Archive {archive_path.name} does not start with expected prefix '{prefix}'"
        )
    remainder = name[len(prefix):]

    parts = remainder.split("-")
    version_idx = None
    for i, part in enumerate(parts):
        if part and part[0].isdigit():
            version_idx = i
            break

    if version_idx is None or version_idx == 0:
        raise ValueError(f"Could not parse platform/version from {archive_path.name}")

    platform_name = "-".join(parts[:version_idx])
    raw_version = "-".join(parts[version_idx:])
    return platform_name, normalize_version(raw_version)


def stage_package(staging_dir: Path, extracted: Path, version: str) -> None:
    """Copy repo sources + extracted bin/share into the build staging directory."""
    src_pkg = REPO_ROOT / "openocd_esp32"
    dst_pkg = staging_dir / "openocd_esp32"
    shutil.copytree(
        src_pkg,
        dst_pkg,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "_version.py"),
    )
    (dst_pkg / "_version.py").write_text(
        '# SPDX-License-Identifier: GPL-2.0-or-later\n\n'
        '"""Package version. Generated by tools/build_wheel.py."""\n\n'
        f'__version__ = "{version}"\n'
    )

    shutil.copy2(REPO_ROOT / "pyproject.toml", staging_dir / "pyproject.toml")

    for required in ("README.md", "COPYING"):
        src = REPO_ROOT / required
        if not src.is_file():
            raise RuntimeError(f"Required file not found in repo root: {required}")
        shutil.copy2(src, staging_dir / required)

    bin_src = extracted / "bin"
    if not bin_src.is_dir():
        raise RuntimeError(f"Expected bin/ directory not found in {extracted}")
    shutil.copytree(bin_src, dst_pkg / "bin", ignore_dangling_symlinks=True)

    share_src = extracted / "share"
    if not share_src.is_dir():
        raise RuntimeError(f"Expected share/ directory not found in {extracted}")
    shutil.copytree(share_src, dst_pkg / "share", ignore_dangling_symlinks=True)


def build_wheel(archive_path: Path, output_dir: Path, project_prefix: str) -> Path:
    """Build a platform-tagged wheel from the distribution archive."""
    platform_name, version = parse_archive_name(archive_path, project_prefix)

    if platform_name not in PLATFORM_MAP:
        raise ValueError(
            f"Unknown platform '{platform_name}'. "
            f"Known: {sorted(PLATFORM_MAP)}"
        )
    wheel_platform = PLATFORM_MAP[platform_name]

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    work_dir = output_dir / f".build-{platform_name}-{version}"
    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True)

    try:
        extracted = extract_archive(archive_path, work_dir / "extracted")
        staging = work_dir / "staging"
        staging.mkdir()
        stage_package(staging, extracted, version)

        subprocess.run(
            [
                sys.executable, "-m", "pip", "wheel",
                str(staging),
                "-w", str(work_dir / "wheels"),
                "--no-deps",
            ],
            check=True,
        )

        built_wheels = list((work_dir / "wheels").glob("openocd_esp32-*.whl"))
        if len(built_wheels) != 1:
            raise RuntimeError(
                f"Expected exactly one wheel, found {len(built_wheels)}: {built_wheels}"
            )
        any_wheel = built_wheels[0]

        subprocess.run(
            [
                sys.executable, "-m", "wheel", "tags",
                "--platform-tag", wheel_platform,
                "--remove",
                str(any_wheel),
            ],
            check=True,
            cwd=work_dir / "wheels",
        )

        retagged = list((work_dir / "wheels").glob("openocd_esp32-*.whl"))
        if len(retagged) != 1:
            raise RuntimeError(
                f"Expected exactly one retagged wheel, found: {retagged}"
            )
        final_wheel = retagged[0]
        if "-any.whl" in final_wheel.name:
            raise RuntimeError(
                f"Wheel still has 'any' platform tag after retag: {final_wheel.name}"
            )

        dest = output_dir / final_wheel.name
        if dest.exists():
            dest.unlink()
        shutil.move(str(final_wheel), str(dest))
        return dest
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description="Build wheel from OpenOCD archive")
    parser.add_argument("archive", type=Path, help="Path to distribution archive")
    parser.add_argument("output", type=Path, help="Output directory for wheel")
    parser.add_argument(
        "--project-prefix",
        default="openocd-esp32",
        help="Expected project prefix in archive name (default: openocd-esp32)",
    )

    args = parser.parse_args()

    if not args.archive.is_file():
        sys.exit(f"Error: archive not found: {args.archive}")

    wheel_path = build_wheel(args.archive, args.output, args.project_prefix)
    print(f"Built: {wheel_path}")


if __name__ == "__main__":
    main()
